### ISSUE TITLE
curl errors from no 'clone.bundle'

### ISSUE THREAD

**Issue by jeremiah** [amirna2/genivi-manifest#2]
I get this error a lot when using the repo tool;

"curl: (22) The requested URL returned error: 404 Not Found
Server does not provide clone.bundle; ignoring."

I assume it is no big deal, right?

**Comment by amirna2** [comment]
Repo is attempting to optimize the git fetch by cloning a bundle (I think this is a prepackaged set of files provided by some git servers). If a bundle file isn't available (like in this case), repo will ignore it and proceed anyway. So it is just a warning and you can safely ignore these messages.
